<a href="https://colab.research.google.com/github/fabricio136900/M3_Data/blob/RunIT/Trabajo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Importación de librerías

In [ ]:
import pandas as pd #Manipula y analiza datos en tablas (filas y columnas).
import numpy as np #Soporta operaciones matemáticas con arrays y matrices.
import matplotlib.pyplot as plt #Genera gráficos como líneas, barras y dispersión.
import seaborn as sns #Crea visualizaciones estadísticas más estilizadas y fáciles de interpretar.
import gdown #Permite descargar archivos desde Google Drive.

###Cargar el dataset de Kaggle

In [ ]:
# prompt: conexion con google drive
from google.colab import drive
drive.mount('/content/drive')

#link Kaggle: https://www.kaggle.com/datasets/andrexibiza/grocery-sales-dataset?select=sales.csv

Mounted at /content/drive

In [ ]:
dt1 = pd.read_csv('/content/drive/MyDrive/My/04 diplox/103 Bigdata/Trabajo 01/Base de Datos/trabajo /sales.csv')
dt2 = pd.read_csv('/content/drive/MyDrive/My/04 diplox/103 Bigdata/Trabajo 01/Base de Datos/trabajo /products.csv')
dt3 = pd.read_csv('/content/drive/MyDrive/My/04 diplox/103 Bigdata/Trabajo 01/Base de Datos/trabajo /customers.csv')
dt4 = pd.read_csv('/content/drive/MyDrive/My/04 diplox/103 Bigdata/Trabajo 01/Base de Datos/trabajo /employees.csv')

###Opción 2 de cargar el dataset de Kaggle

In [ ]:
# Instalar gdown si es necesario para la dirección link
!pip install gdown

# Diccionario con nombre de archivo y su URL de Google Drive (formato 'uc?id=...')
files = {
    "sales.csv":     "1cm0CjyBp9ieb3o-PkZA8u_jn7rYjV_EW",
    "products.csv":  "1-QYE4L8bsv5wedAFh8uetfKHJsTwoI9h",
    "customers.csv": "1bzxl9pM5lmQiMcysPAqlnOnhouecSIFP",
    "employees.csv": "1IyZu6PIdLOPxkhELrCFhO8iYhvvjdMyn"
}
# Descargar todos los archivos
for filename, file_id in files.items():
    url = f"https://drive.google.com/uc?id={file_id}"
    gdown.download(url, filename, quiet=False)

Requirement already satisfied: gdown in /usr/local/lib/python3.11/dist-packages (5.2.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from gdown) (4.13.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from gdown) (3.18.0)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.11/dist-packages (from gdown) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from gdown) (4.67.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->gdown) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->gdown) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (2025.4.26)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (1.7.1)

Downloading...
From (original): https://drive.google.com/uc?id=1cm0CjyBp9ieb3o-PkZA8u_jn7rYjV_EW
From (redirected): https://drive.google.com/uc?id=1cm0CjyBp9ieb3o-PkZA8u_jn7rYjV_EW&confirm=t&uuid=3bfb4fbd-905f-4878-ad71-e24844227195
To: /content/sales.csv

  0%|          | 0.00/517M [00:00<?, ?B/s]
  1%|          | 5.77M/517M [00:00<00:09, 54.4MB/s]
  2%|▏         | 11.5M/517M [00:00<00:10, 47.7MB/s]
  3%|▎         | 16.8M/517M [00:00<00:13, 37.2MB/s]
  5%|▍         | 24.6M/517M [00:00<00:10, 48.1MB/s]
  9%|▊         | 44.0M/517M [00:00<00:08, 54.5MB/s]
 12%|█▏        | 62.4M/517M [00:00<00:05, 80.0MB/s]
 14%|█▍        | 73.4M/517M [00:01<00:05, 86.7MB/s]
 16%|█▋        | 84.4M/517M [00:01<00:04, 91.8MB/s]
 18%|█▊        | 94.9M/517M [00:01<00:06, 69.7MB/s]
 21%|██        | 107M/517M [00:01<00:05, 75.7MB/s]
 22%|██▏       | 116M/517M [00:01<00:07, 54.7MB/s]
 25%|██▌       | 131M/517M [00:01<00:05, 70.9MB/s]
 28%|██▊       | 144M/517M [00:02<00:04, 82.8MB/s]
 30%|██▉       | 154M/517M [00:02<00:04, 83.2MB/s]
 32%|███▏      | 164M/517M [00:02<00:05, 67.8MB/s]
 36%|███▌      | 185M/517M [00:02<00:03, 91.3MB/s]
 38%|███▊      | 198M/517M [00:02<00:04, 73.8MB/s]
 42%|████▏     | 215M/517M [00:02<00:03, 91.3MB/s]
 44%|████▍     | 229M/517M [00:03<00:04, 63.1MB/s]
 48%|████▊     | 247M/517M [00:03<00:03, 80.9MB/s]
 50%|████▉     | 258M/517M [00:03<00:03, 71.0MB/s]
 55%|█████▍    | 283M/517M [00:03<00:02, 88.5MB/s]
 57%|█████▋    | 296M/517M [00:03<00:02, 94.9MB/s]
 60%|██████    | 310M/517M [00:03<00:01, 105MB/s]
 62%|██████▏   | 323M/517M [00:04<00:02, 88.2MB/s]
 64%|██████▍   | 333M/517M [00:04<00:02, 87.6MB/s]
 68%|██████▊   | 350M/517M [00:04<00:01, 97.3MB/s]
 70%|██████▉   | 361M/517M [00:04<00:01, 86.3MB/s]
 74%|███████▎  | 381M/517M [00:04<00:01, 109MB/s]
 76%|███████▋  | 395M/517M [00:05<00:02, 55.2MB/s]
 81%|████████  | 416M/517M [00:05<00:01, 77.0MB/s]
 83%|████████▎ | 429M/517M [00:07<00:04, 17.7MB/s]
 85%|████████▍ | 439M/517M [00:07<00:03, 21.4MB/s]
 88%|████████▊ | 456M/517M [00:08<00:02, 28.0MB/s]
 90%|████████▉ | 465M/517M [00:08<00:01, 31.9MB/s]
 91%|█████████▏| 473M/517M [00:08<00:01, 35.7MB/s]
 93%|█████████▎| 482M/517M [00:08<00:00, 41.1MB/s]
 95%|█████████▍| 490M/517M [00:08<00:00, 35.2MB/s]
 97%|█████████▋| 502M/517M [00:09<00:00, 39.2MB/s]
100%|██████████| 517M/517M [00:09<00:00, 55.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=1-QYE4L8bsv5wedAFh8uetfKHJsTwoI9h
To: /content/products.csv

100%|██████████| 36.8k/36.8k [00:00<00:00, 46.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=1bzxl9pM5lmQiMcysPAqlnOnhouecSIFP
To: /content/customers.csv

100%|██████████| 4.44M/4.44M [00:00<00:00, 206MB/s]

### Cargar DataSet de Kaggle

In [9]:
# Cargar datasets con pandas
dt1 = pd.read_csv('sales.csv')
dt2 = pd.read_csv('products.csv')
dt3 = pd.read_csv('customers.csv')
dt4 = pd.read_csv('employees.csv')

###Conversión a DataFrames

In [ ]:
df1 = pd.DataFrame(dt1)
df2 = pd.DataFrame(dt2)
df3 = pd.DataFrame(dt3)
df4 = pd.DataFrame(dt4)

###Dimensiones de los DataFrames

In [ ]:
print(df1.shape)
print(df2.shape)
print(df3.shape)
print(df4.shape)

(6758125, 9)
(452, 9)
(98759, 6)
(23, 8)

## b) Análisis Exploratorio de Datos (AED)

### *Variables de la tabla Sales (Ventas)

In [ ]:
print(df1.head(3))

   SalesID  SalesPersonID  CustomerID  ProductID  Quantity  Discount  \
0        1              6       27039        381         7       0.0
1        2             16       25011         61         7       0.0
2        3             13       94024         23        24       0.0

   TotalPrice                SalesDate     TransactionNumber
0         0.0  2018-02-05 07:38:25.430  FQL4S94E4ME1EZFTG42G
1         0.0  2018-02-02 16:03:31.150  12UGLX40DJ1A5DTFBHB8
2         0.0  2018-05-03 19:31:56.880  5DT8RCPL87KI5EORO7B0

### *Variables de la tabla Products (Productos)

In [ ]:
print(df2.head(3))

   ProductID                 ProductName    Price  CategoryID   Class  \
0          1         Flour - Whole Wheat  74.2988           3  Medium
1          2  Cookie Chocolate Chip With  91.2329           3  Medium
2          3          Onions - Cippolini   9.1379           9  Medium

                ModifyDate Resistant IsAllergic  VitalityDays
0  2018-02-16 08:21:49.190   Durable    Unknown           0.0
1  2017-02-12 11:39:10.970   Unknown    Unknown           0.0
2  2018-03-15 08:11:51.560      Weak      False         111.0

### *Variables de la tabla Customers (Clientes)

In [ ]:
print(df3.tail(3))

       CustomerID FirstName MiddleInitial LastName  CityID             Address
98756       98757     Shari             J   Prince      81    791 Milton Drive
98757       98758    Stuart             K  Cameron      57  149 Clarendon Road
98758       98759    Willie             E   Lawson      94   50 Fabien Freeway

In [ ]:
print(df4.tail(3)) # Tabla Empleados

    EmployeeID FirstName MiddleInitial   LastName                BirthDate  \
20          21     Devon             D     Brewer  1966-04-25 00:00:00.000
21          22     Tonia             O  Mc Millan  1952-03-02 00:00:00.000
22          23     Janet             K    Flowers  1979-03-01 00:00:00.000

   Gender  CityID                 HireDate
20      M      65  2016-01-24 02:13:24.340
21      F      53  2015-11-25 18:18:23.480
22      F       7  2010-05-12 02:52:30.370

### *Tipo de Datos de cada tabla

In [ ]:
print(df1.dtypes) # Tabla Ventas

SalesID                int64
SalesPersonID          int64
CustomerID             int64
ProductID              int64
Quantity               int64
Discount             float64
TotalPrice           float64
SalesDate             object
TransactionNumber     object
dtype: object

In [ ]:
print(df2.dtypes) # Tabla Productos

ProductID         int64
ProductName      object
Price           float64
CategoryID        int64
Class            object
ModifyDate       object
Resistant        object
IsAllergic       object
VitalityDays    float64
dtype: object

In [ ]:
print(df3.dtypes) # Tabla Clientes

CustomerID        int64
FirstName        object
MiddleInitial    object
LastName         object
CityID            int64
Address          object
dtype: object

In [ ]:
print(df4.dtypes) # Tabla Empleados

EmployeeID        int64
FirstName        object
MiddleInitial    object
LastName         object
BirthDate        object
Gender           object
CityID            int64
HireDate         object
dtype: object

###Clase y Longitud

In [ ]:
print(type(df1))
print(type(df2))
print(type(df3))
print(type(df4))

print(len(df1))
print(len(df2))
print(len(df3))
print(len(df4))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
6758125
452
98759
23

###Listado de columnas por tabla

In [ ]:
print(df1.columns) #ventas
print('------------------------------------------')
print(df2.columns) #productos
print('------------------------------------------')
print(df3.columns) #clientes
print('------------------------------------------')
print(df4.columns) #empleados

Index(['SalesID', 'SalesPersonID', 'CustomerID', 'ProductID', 'Quantity',
       'Discount', 'TotalPrice', 'SalesDate', 'TransactionNumber'],
      dtype='object')
------------------------------------------
Index(['ProductID', 'ProductName', 'Price', 'CategoryID', 'Class',
       'ModifyDate', 'Resistant', 'IsAllergic', 'VitalityDays'],
      dtype='object')
------------------------------------------
Index(['CustomerID', 'FirstName', 'MiddleInitial', 'LastName', 'CityID',
       'Address'],
      dtype='object')
------------------------------------------
Index(['EmployeeID', 'FirstName', 'MiddleInitial', 'LastName', 'BirthDate',
       'Gender', 'CityID', 'HireDate'],
      dtype='object')

### *Cantidad de nulos por tabla

In [ ]:
null_counts_df1 = df1.isnull().sum()
null_counts_df2 = df2.isnull().sum()
null_counts_df3 = df3.isnull().sum()
null_counts_df4 = df4.isnull().sum()

print(f'Nulos de ventas:{null_counts_df1}')
print('------------------------------------------')
print(f'Nulos de Productos:{null_counts_df2}')
print('------------------------------------------')
print(f'Nulos de Clientes: {null_counts_df3}')
print('------------------------------------------')
print(f'Nulos de Clientes: {null_counts_df4}')

Nulos de ventas:SalesID                  0
SalesPersonID            0
CustomerID               0
ProductID                0
Quantity                 0
Discount                 0
TotalPrice               0
SalesDate            67526
TransactionNumber        0
dtype: int64
------------------------------------------
Nulos de Productos:ProductID       0
ProductName     0
Price           0
CategoryID      0
Class           0
ModifyDate      0
Resistant       0
IsAllergic      0
VitalityDays    0
dtype: int64
------------------------------------------
Nulos de Clientes: CustomerID         0
FirstName          0
MiddleInitial    977
LastName           0
CityID             0
Address            0
dtype: int64
------------------------------------------
Nulos de Clientes: EmployeeID       0
FirstName        0
MiddleInitial    0
LastName         0
BirthDate        0
Gender           0
CityID           0
HireDate         0
dtype: int64

### Limpieza de nulos en columnas clave

In [ ]:
df1_cleaned = df1.dropna(subset=['SalesDate'])
df3_cleaned = df3.dropna(subset=['MiddleInitial'])

print(df1_cleaned.shape)
print(df3_cleaned.shape)

(6690599, 9)
(97782, 6)

### Estadistica básica
* Media
* Mediana
* Moda
* Rango Maximo y minimo
* Cuartiles
* RIC - rango intercuartil
* Varianza
* Desviacion Estandar

### Media
Cual es la media de las variable cuantitativas de la variable df1_cleaned (sales), df3_cleaned (clientes)

In [ ]:
df1_mean1 = df1_cleaned['TotalPrice'].mean()
df1_mean2 = df1_cleaned['Discount'].mean()
print(df1_mean1)
print(df1_mean2)

0.0
0.029964581646576043

### Mediana

### Moda

### Rango Max y Min

### Cuartiles

### RIC -Rango Intercuartil

### Varianza

### Desviación Estandar

## c) Preparación de Datos por Columnas

### Conversión de tipos de datos (por ejemplo, fechas o categorías).

In [ ]:
df1_cleaned.head(3)

,SalesID,SalesPersonID,CustomerID,ProductID,Quantity,Discount,TotalPrice,SalesDate,TransactionNumber
0,1,6,27039,381,7,0.0,0.0,2018-02-05 07:38:25.430,FQL4S94E4ME1EZFTG42G
1,2,16,25011,61,7,0.0,0.0,2018-02-02 16:03:31.150,12UGLX40DJ1A5DTFBHB8
2,3,13,94024,23,24,0.0,0.0,2018-05-03 19:31:56.880,5DT8RCPL87KI5EORO7B0

In [ ]:
print(df1_cleaned.dtypes)

SalesID                int64
SalesPersonID          int64
CustomerID             int64
ProductID              int64
Quantity               int64
Discount             float64
TotalPrice           float64
SalesDate             object
TransactionNumber     object
dtype: object

In [ ]:
df1_cleaned['SalesDate'] = pd.to_datetime(df1_cleaned['SalesDate'],)

<ipython-input-25-caa0d9219f4d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_cleaned['SalesDate'] = pd.to_datetime(df1_cleaned['SalesDate'],)

In [ ]:
print(df1_cleaned.dtypes)

SalesID                       int64
SalesPersonID                 int64
CustomerID                    int64
ProductID                     int64
Quantity                      int64
Discount                    float64
TotalPrice                  float64
SalesDate            datetime64[ns]
TransactionNumber            object
dtype: object

In [ ]:
df1_cleaned['Fecha'] = df1_cleaned['SalesDate'].dt.date

<ipython-input-27-1826be725886>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_cleaned['Fecha'] = df1_cleaned['SalesDate'].dt.date

In [ ]:
df1_cleaned['hora'] = df1_cleaned['SalesDate'].dt.time

<ipython-input-28-896adcde9d90>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_cleaned['hora'] = df1_cleaned['SalesDate'].dt.time

In [ ]:
df1_cleaned.to_csv('archivo_modificado.csv', index=False)

In [ ]:
print(df1_cleaned[['Fecha', 'hora']].head(3))

        Fecha             hora
0  2018-02-05  07:38:25.430000
1  2018-02-02  16:03:31.150000
2  2018-05-03  19:31:56.880000

In [ ]:
df1_cleaned_Fechahora= df1_cleaned[['Fecha', 'hora']]

In [ ]:
print(df1_cleaned_Fechahora.head(3))

        Fecha             hora
0  2018-02-05  07:38:25.430000
1  2018-02-02  16:03:31.150000
2  2018-05-03  19:31:56.880000

In [ ]:
# adecuacion de la tabla 'emploees'
# df4_cleaned = df4.dropna(subset=['MiddleInitial'])
#print(df4.dtypes)
print(df4['BirthDate'].head(2))
#df4['BirthDate'] = df4['BirthDate'].dt.date
df4['BirthDate'] = pd.to_datetime(df4['BirthDate'])
df4['HireDate'] = pd.to_datetime(df4['HireDate'])
print('------------------------------------------')
print(df4['BirthDate'].head(2))
print(df4['HireDate'].head(2))
print('------------------------------------------')
print(df4['BirthDate'].dtypes, " -- ",df4['HireDate'].dtypes)

0   1981-03-07
1   1968-01-25
Name: BirthDate, dtype: datetime64[ns]
------------------------------------------
0   1981-03-07
1   1968-01-25
Name: BirthDate, dtype: datetime64[ns]
0   2011-06-20 07:15:36.920
1   2011-04-27 04:07:56.930
Name: HireDate, dtype: datetime64[ns]
------------------------------------------
datetime64[ns]  --  datetime64[ns]

### Imputación de valores faltantes.

In [ ]:
precio_dict = dict(zip(df2['ProductID'], df2['Price']))

#Asignar precios a la tabla de ventas
df1_cleaned ['Price'] = df1_cleaned['ProductID'].map(precio_dict)

#Insertar la columna precio en la posicion deseada
df1_cleaned.insert(5, 'Price', df1_cleaned.pop('Price'))

#Agregar la columna subtotal
df1_cleaned ['SubTotal'] = df1_cleaned['Price'] * df1_cleaned['Quantity']

<ipython-input-39-255b3d266f8d>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_cleaned ['Price'] = df1_cleaned['ProductID'].map(precio_dict)
<ipython-input-39-255b3d266f8d>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_cleaned ['SubTotal'] = df1_cleaned['Price'] * df1_cleaned['Quantity']

In [ ]:
print(df1_cleaned.head(3))

   SalesID  SalesPersonID  CustomerID  ProductID  Quantity    Price  Discount  \
0        1              6       27039        381         7  44.2337       0.0
1        2             16       25011         61         7  62.5460       0.0
2        3             13       94024         23        24  79.0184       0.0

   TotalPrice               SalesDate     TransactionNumber       Fecha  \
0         0.0 2018-02-05 07:38:25.430  FQL4S94E4ME1EZFTG42G  2018-02-05
1         0.0 2018-02-02 16:03:31.150  12UGLX40DJ1A5DTFBHB8  2018-02-02
2         0.0 2018-05-03 19:31:56.880  5DT8RCPL87KI5EORO7B0  2018-05-03

              hora   SubTotal
0  07:38:25.430000   309.6359
1  16:03:31.150000   437.8220
2  19:31:56.880000  1896.4416

In [ ]:
print (df1_cleaned['SubTotal'].median())

print (df1_cleaned['SubTotal'].max())

print (df1_cleaned['SubTotal'].min())

507.33410000000003
2496.8875000000003
0.0449

## Criterio para la columna descuentos en ventas
* Ventas de 2500 5 % de descuento
* Ventas de 1000 3 % de descuento
* Ventas de 750  0.5 % de descuento

In [ ]:
def calcular_descuento(subtotal):
    if subtotal >= 2500:
        return subtotal * 0.05
    elif subtotal >= 1000 and subtotal <= 1999:
        return subtotal * 0.03
    elif subtotal >= 750 and subtotal <= 999:
        return subtotal * 0.005
    else:
        return 0

In [ ]:
df1_cleaned['Discount'] = df1_cleaned['SubTotal'].apply(calcular_descuento)

<ipython-input-43-1945b84b45d3>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_cleaned['Discount'] = df1_cleaned['SubTotal'].apply(calcular_descuento)

In [ ]:
print(df1_cleaned.head(3))
#print (df1_cleaned.head(3))

   SalesID  SalesPersonID  CustomerID  ProductID  Quantity    Price  \
0        1              6       27039        381         7  44.2337
1        2             16       25011         61         7  62.5460
2        3             13       94024         23        24  79.0184

    Discount  TotalPrice               SalesDate     TransactionNumber  \
0   0.000000         0.0 2018-02-05 07:38:25.430  FQL4S94E4ME1EZFTG42G
1   0.000000         0.0 2018-02-02 16:03:31.150  12UGLX40DJ1A5DTFBHB8
2  56.893248         0.0 2018-05-03 19:31:56.880  5DT8RCPL87KI5EORO7B0

        Fecha             hora   SubTotal
0  2018-02-05  07:38:25.430000   309.6359
1  2018-02-02  16:03:31.150000   437.8220
2  2018-05-03  19:31:56.880000  1896.4416

In [ ]:
df1_cleaned['TotalPrice'] = df1_cleaned['SubTotal'] - df1_cleaned['Discount']
print(df1_cleaned.head(3))

   SalesID  SalesPersonID  CustomerID  ProductID  Quantity    Price  \
0        1              6       27039        381         7  44.2337
1        2             16       25011         61         7  62.5460
2        3             13       94024         23        24  79.0184

    Discount   TotalPrice               SalesDate     TransactionNumber  \
0   0.000000   309.635900 2018-02-05 07:38:25.430  FQL4S94E4ME1EZFTG42G
1   0.000000   437.822000 2018-02-02 16:03:31.150  12UGLX40DJ1A5DTFBHB8
2  56.893248  1839.548352 2018-05-03 19:31:56.880  5DT8RCPL87KI5EORO7B0

        Fecha             hora   SubTotal
0  2018-02-05  07:38:25.430000   309.6359
1  2018-02-02  16:03:31.150000   437.8220
2  2018-05-03  19:31:56.880000  1896.4416

<ipython-input-45-2b5856c18082>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_cleaned['TotalPrice'] = df1_cleaned['SubTotal'] - df1_cleaned['Discount']

### Creación o transformación de nuevas columnas.

In [ ]:
# En la tabla 'employee' vamos a calcular la edad de los empleados considerando mayo del 2025
df4['Edad_empleado'] = 2025 - df4['BirthDate'].dt.year
print(df4.columns)

Index(['EmployeeID', 'FirstName', 'MiddleInitial', 'LastName', 'BirthDate',
       'Gender', 'CityID', 'HireDate', 'Edad_empleado'],
      dtype='object')

In [ ]:
## verificamos el contenido de la nueva columna creada
print(df4['Edad_empleado'].head(3))

0    44
1    57
2    62
Name: Edad_empleado, dtype: int32

In [ ]:
## calculamos en la tabla 'employee' el tiepo trabajado de cada empleado
df4['Antiguedad_employee'] = 2025 - df4['HireDate'].dt.year
print(df4.columns)
print('------------------------------------------')
print(df4['Antiguedad_employee'].head(3))

Index(['EmployeeID', 'FirstName', 'MiddleInitial', 'LastName', 'BirthDate',
       'Gender', 'CityID', 'HireDate', 'Edad_empleado', 'Antiguedad_employee'],
      dtype='object')
------------------------------------------
0    14
1    14
2    13
Name: Antiguedad_employee, dtype: int32

In [ ]:
## vamos a ordern y agrupar por mejor vendedor usando las tablas 'sales' y 'employee'.
df5 = df1_cleaned
print(df5.head(3))

## incorporamos los datos de employee en df5 del empleado, nombre, edad y antiguedad.
data_empl = dict(zip(df4['EmployeeID'], zip(df4['FirstName'], df4['Edad_empleado'], df4['Antiguedad_employee'])))

## asignamos las nuevas columnas con las consultas necesarias
df5['FirstName'] = df5['SalesPersonID'].map(lambda x: data_empl[x][0])
df5['Edad_empleado'] = df5['SalesPersonID'].map(lambda x: data_empl[x][1])
df5['Antiguedad_employee'] = df5['SalesPersonID'].map(lambda x: data_empl[x][2])

## verificamos el contenido de la nueva columna creada
print(df5.columns)

   SalesID  SalesPersonID  CustomerID  ProductID  Quantity    Price  \
0        1              6       27039        381         7  44.2337
1        2             16       25011         61         7  62.5460
2        3             13       94024         23        24  79.0184

    Discount   TotalPrice               SalesDate     TransactionNumber  \
0   0.000000   309.635900 2018-02-05 07:38:25.430  FQL4S94E4ME1EZFTG42G
1   0.000000   437.822000 2018-02-02 16:03:31.150  12UGLX40DJ1A5DTFBHB8
2  56.893248  1839.548352 2018-05-03 19:31:56.880  5DT8RCPL87KI5EORO7B0

        Fecha             hora   SubTotal FirstName  Edad_empleado  \
0  2018-02-05  07:38:25.430000   309.6359     Holly             38
1  2018-02-02  16:03:31.150000   437.8220  Chadwick             74
2  2018-05-03  19:31:56.880000  1896.4416    Katina             62

   Antiguedad_employee
0                   12
1                    8
2                   14

<ipython-input-59-8c69780c9cf6>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5['FirstName'] = df5['SalesPersonID'].map(lambda x: data_empl[x][0])
<ipython-input-59-8c69780c9cf6>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5['Edad_empleado'] = df5['SalesPersonID'].map(lambda x: data_empl[x][1])

Index(['SalesID', 'SalesPersonID', 'CustomerID', 'ProductID', 'Quantity',
       'Price', 'Discount', 'TotalPrice', 'SalesDate', 'TransactionNumber',
       'Fecha', 'hora', 'SubTotal', 'FirstName', 'Edad_empleado',
       'Antiguedad_employee'],
      dtype='object')

<ipython-input-59-8c69780c9cf6>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5['Antiguedad_employee'] = df5['SalesPersonID'].map(lambda x: data_empl[x][2])

In [ ]:
df5.head(3)

,SalesID,SalesPersonID,CustomerID,ProductID,Quantity,Price,Discount,TotalPrice,SalesDate,TransactionNumber,Fecha,hora,SubTotal,FirstName,Edad_empleado,Antiguedad_employee
0,1,6,27039,381,7,44.2337,0.000000,309.635900,2018-02-05 07:38:25.430,FQL4S94E4ME1EZFTG42G,2018-02-05,07:38:25.430000,309.6359,Holly,38,12
1,2,16,25011,61,7,62.5460,0.000000,437.822000,2018-02-02 16:03:31.150,12UGLX40DJ1A5DTFBHB8,2018-02-02,16:03:31.150000,437.8220,Chadwick,74,8
2,3,13,94024,23,24,79.0184,56.893248,1839.548352,2018-05-03 19:31:56.880,5DT8RCPL87KI5EORO7B0,2018-05-03,19:31:56.880000,1896.4416,Katina,62,14

In [ ]:
df5_grouped = df5.sort_values("FirstName", ascending=False)
print(df_ordenado.tail(3))

## d) Preparación de Datos por Filas

### Eliminación de duplicados.

Eliminacion de duplicados para la tabla productos

In [ ]:
# Conteo de duplicados basado en columnas clave (ej. 'TransactionNumber')
# Un número de transacción debería ser único para cada venta.
num_duplicados_transaction = df1_cleaned.duplicated(subset=['TransactionNumber']).sum()
print(f"\nNúmero de filas duplicadas basadas en 'TransactionNumber': {num_duplicados_transaction}")

In [ ]:
#Eliminar duplicados en df1_cleaned (Ventas) basados en 'TransactionNumber'
# Un TransactionNumber debería ser único para cada venta.
print(f"Filas en df1_cleaned antes de eliminar duplicados por 'TransactionNumber': {len(df1_cleaned)}")
df1_ventas_unicas = df1_cleaned.drop_duplicates(subset=['TransactionNumber'], keep='first').copy()
print(f"Filas en df1_ventas_unicas después de eliminar duplicados por 'TransactionNumber': {len(df1_ventas_unicas)}")
print("\nPrimeras filas de df1_ventas_unicas después de la limpieza de duplicados:")
print(df1_ventas_unicas.head())

In [ ]:
#Eliminar duplicados en df3_cleaned (Clientes) basados en 'CustomerID'
# Cada Cliente_ID debería ser único.
print(f"\nFilas en df3_cleaned antes de eliminar duplicados por 'CustomerID': {len(df3_cleaned)}")
df3_clientes_unicos = df3_cleaned.drop_duplicates(subset=['CustomerID'], keep='first').copy()
print(f"Filas en df3_clientes_unicos después de eliminar duplicados por 'CustomerID': {len(df3_clientes_unicos)}")
print("\nPrimeras filas de df3_clientes_unicos después de la limpieza de duplicados:")
print(df3_clientes_unicos.head())

print("\n" + "="*80 + "\n")

In [ ]:
#Eliminar duplicados en df2 (Productos) basados en 'ProductID'
# Cada ProductID debería ser único.
print(f"\nFilas en df2 antes de eliminar duplicados por 'ProductID': {len(df2)}")
df2_productos_unicos = df2.drop_duplicates(subset=['ProductID'], keep='first').copy()
print(f"Filas en df2_productos_unicos después de eliminar duplicados por 'ProductID': {len(df2_productos_unicos)}")
print("\nPrimeras filas de df2_productos_unicos después de la limpieza de duplicados:")
print(df2_productos_unicos.head())


print("\n" + "="*80 + "\n")

### Filtrado de registros irrelevantes o fuera de rango

In [ ]:
df1_ventas_validas = df1_ventas_unicas[df1_ventas_unicas['TotalPrice'] > 0].copy()
print(f"Filas en df1_ventas_unicas antes de filtrar por TotalPrice > 0: {len(df1_ventas_unicas)}")
print(f"Filas en df1_ventas_validas después de filtrar TotalPrice > 0: {len(df1_ventas_validas)}")
print("\nPrimeras filas de df1_ventas_validas:")
print(df1_ventas_validas.head())

In [ ]:
# Un precio de producto de 0 o negativo no tiene sentido comercial.
df2_productos_validos = df2[df2['Price'] > 0].copy()
print(f"\nFilas en df2 antes de filtrar por Price > 0: {len(df2)}")
print(f"Filas en df2_productos_validos después de filtrar Price > 0: {len(df2_productos_validos)}")
print("\nPrimeras filas de df2_productos_validos:")
print(df2_productos_validos.head())

In [ ]:
# Asumiendo que queremos clientes de una ciudad específica, por ejemplo, CityID == 1
df3_clientes_ciudad1 = df3_clientes_unicos[df3_clientes_unicos['CityID'] == 1].copy()
print(f"\nFilas en df3_clientes_unicos antes de filtrar por CityID == 1: {len(df3_clientes_unicos)}")
print(f"Filas en df3_clientes_ciudad1 (CityID == 1): {len(df3_clientes_ciudad1)}")
print("\nPrimeras filas de df3_clientes_ciudad1:")
print(df3_clientes_ciudad1.head())

In [ ]:
# Filtrar ventas por un rango de fechas (ej. solo ventas de abril de 2018)
# Asegúrate de que 'SalesDate' sea tipo datetime.
df1_ventas_abril_2018 = df1_ventas_validas[
    (df1_ventas_validas['SalesDate'].dt.year == 2018) &
    (df1_ventas_validas['SalesDate'].dt.month == 4)
].copy()
print(f"\nFilas en df1_ventas_validas antes de filtrar por abril 2018: {len(df1_ventas_validas)}")
print(f"Filas en df1_ventas_abril_2018: {len(df1_ventas_abril_2018)}")
print("\nPrimeras filas de df1_ventas_abril_2018:")
print(df1_ventas_abril_2018.head())

print("\n" + "="*80 + "\n")

In [ ]:
#Filtrar productos en df2_productos_validos por 'Class' (ej. solo productos 'Medium')
df2_productos_medium = df2_productos_validos[df2_productos_validos['Class'] == 'Medium'].copy()
print(f"\nFilas en df2_productos_validos antes de filtrar por Class 'Medium': {len(df2_productos_validos)}")
print(f"Filas en df2_productos_medium (Class == 'Medium'): {len(df2_productos_medium)}")
print("\nPrimeras filas de df2_productos_medium:")
print(df2_productos_medium.head())

### Agrupación de datos por categorías temporales, geográficas, etc.

NameError: name 'df1' is not defined