<a href="https://colab.research.google.com/github/fabricio136900/M3_Data/blob/RunIT/Trabajo_1_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Librerias e Importación de Datos

###Importación de librerías

In [2]:
import pandas as pd #Manipula y analiza datos en tablas (filas y columnas).
import numpy as np #Soporta operaciones matemáticas con arrays y matrices.
import matplotlib.pyplot as plt #Genera gráficos como líneas, barras y dispersión.
import seaborn as sns #Crea visualizaciones estadísticas más estilizadas y fáciles de interpretar.
import gdown #Permite descargar archivos desde Google Drive.
from IPython.display import display #Permite mostrar DataFrames de manera más cómoda.
from IPython.display import Markdown #Permite mostrar texto formateado en Jupyter.

### Descargar el dataset de Kaggle

In [3]:
# Instalar gdown si es necesario para la dirección link
!pip install gdown
# Diccionario con nombre de archivo y su URL de Google Drive (formato 'uc?id=...')
files = {
    "sales.csv":     "1cm0CjyBp9ieb3o-PkZA8u_jn7rYjV_EW",
    "products.csv":  "1-QYE4L8bsv5wedAFh8uetfKHJsTwoI9h",
    "customers.csv": "1KnpChWo0rgDsAUwZubkB0Hr4Qcpmfv7U",
    "cities.csv":    "1R-bot4GjUBiuSI2c0AbH2YRWx4NHIMZH"
}
# Descargar todos los archivos
for filename, file_id in files.items():
    url = f"https://drive.google.com/uc?id={file_id}"
    gdown.download(url, filename, quiet=False)

Requirement already satisfied: gdown in /usr/local/lib/python3.11/dist-packages (5.2.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from gdown) (4.13.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from gdown) (3.18.0)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.11/dist-packages (from gdown) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from gdown) (4.67.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->gdown) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->gdown) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (2025.4.26)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (1.7.1)

Downloading...
From (original): https://drive.google.com/uc?id=1cm0CjyBp9ieb3o-PkZA8u_jn7rYjV_EW
From (redirected): https://drive.google.com/uc?id=1cm0CjyBp9ieb3o-PkZA8u_jn7rYjV_EW&confirm=t&uuid=5e768569-c7c4-4685-8635-d734abd224c5
To: /content/sales.csv
100%|██████████| 517M/517M [00:04<00:00, 112MB/s]
Downloading...
From: https://drive.google.com/uc?id=1-QYE4L8bsv5wedAFh8uetfKHJsTwoI9h
To: /content/products.csv
100%|██████████| 36.8k/36.8k [00:00<00:00, 43.2MB/s]
Downloading...
From: https://drive.google.com/uc?id=1KnpChWo0rgDsAUwZubkB0Hr4Qcpmfv7U
To: /content/customers.csv
100%|██████████| 4.73M/4.73M [00:00<00:00, 98.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=1R-bot4GjUBiuSI2c0AbH2YRWx4NHIMZH
To: /content/cities.csv
100%|██████████| 2.69k/2.69k [00:00<00:00, 6.59MB/s]

### Cargar el DataSet de Kaggle

In [4]:
# Cargar datasets con pandas
dt1 = pd.read_csv('sales.csv')
dt2 = pd.read_csv('products.csv')
dt3 = pd.read_csv('customers.csv')
dt5 = pd.read_csv('cities.csv')

###Conversión a DataFrames

In [5]:
df1 = pd.DataFrame(dt1)
df2 = pd.DataFrame(dt2)
df3 = pd.DataFrame(dt3)
df5 = pd.DataFrame(dt5)

###Dimensiones de los DataFrames

In [6]:
print(df1.shape)
print(df2.shape)
print(df3.shape)
print(df5.shape)

(6758125, 9)
(452, 9)
(98759, 7)
(96, 5)

## b) Análisis Exploratorio de Datos (AED)

### Columnas/Variables de la tabla Ventas, Productos, Clientes y Ciudades

In [7]:
display(Markdown("###Ventas"))
display(df1.head(3))
display(Markdown("###Productos"))
display(df2.head(3))
display(Markdown("###Clientes"))
display(df3.head(3))
display(Markdown("###Ciudades"))
display(df5.head(3))

###Ventas

,SalesID,SalesPersonID,CustomerID,ProductID,Quantity,Discount,TotalPrice,SalesDate,TransactionNumber
0,1,6,27039,381,7,0.0,0.0,2018-02-05 07:38:25.430,FQL4S94E4ME1EZFTG42G
1,2,16,25011,61,7,0.0,0.0,2018-02-02 16:03:31.150,12UGLX40DJ1A5DTFBHB8
2,3,13,94024,23,24,0.0,0.0,2018-05-03 19:31:56.880,5DT8RCPL87KI5EORO7B0

###Productos

,ProductID,ProductName,Price,CategoryID,Class,ModifyDate,Resistant,IsAllergic,VitalityDays
0,1,Flour - Whole Wheat,74.2988,3,Medium,2018-02-16 08:21:49.190,Durable,Unknown,0.0
1,2,Cookie Chocolate Chip With,91.2329,3,Medium,2017-02-12 11:39:10.970,Unknown,Unknown,0.0
2,3,Onions - Cippolini,9.1379,9,Medium,2018-03-15 08:11:51.560,Weak,False,111.0

###Clientes

,CustomerID,FirstName,MiddleInitial,LastName,CityID,Address,Gender
0,1,Stefanie,Y,Frye,79.0,97 Oak Avenue,F
1,2,Sandy,T,Kirby,96.0,52 White First Freeway,F
2,3,Lee,T,Zhang,55.0,921 White Fabien Avenue,M

###Ciudades

  CityID CityName Zipcode  CountryID Ubicacion
0      1   Dayton   80563       32.0      Este
1      2  Buffalo   17420       32.0      Este
2      3  Chicago   44751       32.0      Este

### Tipo de Variables/Datos de tabla Ventas, Productos, Clientes y Ciudades

In [13]:
display(Markdown("###Ventas"))
display(df1.dtypes)
display(Markdown("###Productos"))
display(df2.dtypes)
display(Markdown("###Clientes"))
display(df3.dtypes)
display(Markdown("###Ciudades"))
display(df5.dtypes)

###Ventas

SalesID                int64
SalesPersonID          int64
CustomerID             int64
ProductID              int64
Quantity               int64
Discount             float64
TotalPrice           float64
SalesDate             object
TransactionNumber     object
dtype: object

###Productos

ProductID         int64
ProductName      object
Price           float64
CategoryID        int64
Class            object
ModifyDate       object
Resistant        object
IsAllergic       object
VitalityDays    float64
dtype: object

###Clientes

CustomerID        object
FirstName         object
MiddleInitial     object
LastName          object
CityID           float64
Address           object
Gender            object
dtype: object

###Ciudades

CityID        object
CityName      object
Zipcode       object
CountryID    float64
Ubicacion     object
dtype: object

In [14]:
print(df2.dtypes) # Tabla Productos

ProductID         int64
ProductName      object
Price           float64
CategoryID        int64
Class            object
ModifyDate       object
Resistant        object
IsAllergic       object
VitalityDays    float64
dtype: object

In [15]:
print(df3.dtypes) # Tabla Clientes

CustomerID        object
FirstName         object
MiddleInitial     object
LastName          object
CityID           float64
Address           object
Gender            object
dtype: object

###Clase y Longitud

In [17]:
display(Markdown("### Tipos de DataFrames"))
display({
    "df1 (Ventas)": type(df1),
    "df2 (Productos)": type(df2),
    "df3 (Clientes)": type(df3),
    "df5 (Ciudades)": type(df5)
})
display(Markdown("### Cantidad de Filas en Cada DataFrame"))
display({
    "df1 (Ventas)": len(df1),
    "df2 (Productos)": len(df2),
    "df3 (Clientes)": len(df3),
    "df5 (Ciudades)": len(df5)
})

### Tipos de DataFrames

{'df1 (Ventas)': pandas.core.frame.DataFrame,
 'df2 (Productos)': pandas.core.frame.DataFrame,
 'df3 (Clientes)': pandas.core.frame.DataFrame,
 'df5 (Ciudades)': pandas.core.frame.DataFrame}

### Cantidad de Filas en Cada DataFrame

{'df1 (Ventas)': 6758125,
 'df2 (Productos)': 452,
 'df3 (Clientes)': 98759,
 'df5 (Ciudades)': 96}

### Cantidad de nulos por tabla

In [19]:
null_counts_df1 = df1.isnull().sum()
null_counts_df2 = df2.isnull().sum()
null_counts_df3 = df3.isnull().sum()
null_counts_df5 = df5.isnull().sum()
print(f'Nulos de ventas:{null_counts_df1}')
print('------------------------------------------')
print(f'Nulos de Productos:{null_counts_df2}')
print('------------------------------------------')
print(f'Nulos de Clientes: {null_counts_df3}')
print('------------------------------------------')
print(f'Nulos de Empleado: {null_counts_df5}')

Nulos de ventas:SalesID                  0
SalesPersonID            0
CustomerID               0
ProductID                0
Quantity                 0
Discount                 0
TotalPrice               0
SalesDate            67526
TransactionNumber        0
dtype: int64
------------------------------------------
Nulos de Productos:ProductID       0
ProductName     0
Price           0
CategoryID      0
Class           0
ModifyDate      0
Resistant       0
IsAllergic      0
VitalityDays    0
dtype: int64
------------------------------------------
Nulos de Clientes: CustomerID           0
FirstName        95426
MiddleInitial    95467
LastName         95427
CityID           95427
Address          95427
Gender           95427
dtype: int64
------------------------------------------
Nulos de Empleado: CityID       0
CityName     1
Zipcode      1
CountryID    2
Ubicacion    2
dtype: int64

### Limpieza de nulos en columnas clave

In [20]:
# Limpieza: eliminamos solo filas con valores nulos en 'SalesDate' en df1
df1_cleaned = df1.dropna(subset=['SalesDate'])
display(df1_cleaned.head(3))

,SalesID,SalesPersonID,CustomerID,ProductID,Quantity,Discount,TotalPrice,SalesDate,TransactionNumber
0,1,6,27039,381,7,0.0,0.0,2018-02-05 07:38:25.430,FQL4S94E4ME1EZFTG42G
1,2,16,25011,61,7,0.0,0.0,2018-02-02 16:03:31.150,12UGLX40DJ1A5DTFBHB8
2,3,13,94024,23,24,0.0,0.0,2018-05-03 19:31:56.880,5DT8RCPL87KI5EORO7B0

In [21]:
# Limpiar solo las filas con fecha de venta nula
df1_cleaned = df1[df1['SalesDate'].notna()]
display(df1_cleaned.head())

,SalesID,SalesPersonID,CustomerID,ProductID,Quantity,Discount,TotalPrice,SalesDate,TransactionNumber
0,1,6,27039,381,7,0.0,0.0,2018-02-05 07:38:25.430,FQL4S94E4ME1EZFTG42G
1,2,16,25011,61,7,0.0,0.0,2018-02-02 16:03:31.150,12UGLX40DJ1A5DTFBHB8
2,3,13,94024,23,24,0.0,0.0,2018-05-03 19:31:56.880,5DT8RCPL87KI5EORO7B0
3,4,8,73966,176,19,0.2,0.0,2018-04-07 14:43:55.420,R3DR9MLD5NR76VO17ULE
4,5,10,32653,310,9,0.0,0.0,2018-02-12 15:37:03.940,4BGS0Z5OMAZ8NDAFHHP3

In [22]:
display(df3.head(3))

,CustomerID,FirstName,MiddleInitial,LastName,CityID,Address,Gender
0,1,Stefanie,Y,Frye,79.0,97 Oak Avenue,F
1,2,Sandy,T,Kirby,96.0,52 White First Freeway,F
2,3,Lee,T,Zhang,55.0,921 White Fabien Avenue,M

In [23]:
df3_cleaned = df3.dropna(subset=['CityID'])
df3_cleaned['CityID'] = df3_cleaned['CityID'].astype(int)
display(df3_cleaned.head(3))

<ipython-input-23-251df128ce9d>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3_cleaned['CityID'] = df3_cleaned['CityID'].astype(int)

,CustomerID,FirstName,MiddleInitial,LastName,CityID,Address,Gender
0,1,Stefanie,Y,Frye,79,97 Oak Avenue,F
1,2,Sandy,T,Kirby,96,52 White First Freeway,F
2,3,Lee,T,Zhang,55,921 White Fabien Avenue,M

### Análisis Estadístico

### Media

### Mediana

In [24]:
# Cual es la cantidad típica vendida?
median_quantity = df1_cleaned["Quantity"].median()
print(f"La cantidad típica vendida (mediana) es: {median_quantity}")
# Qué descuento es más común entre clientes? (sin que outliers te distorsionen)
median_discount = df1_cleaned["Discount"].median()
print(f"El descuento más común (mediana) es: {median_discount}")
# Cuál es el precio típico pagado por transacción?
median_totalprice = df1_cleaned["TotalPrice"].median()
print(f"El precio típico pagado por transacción (mediana) es: {median_totalprice}")

La cantidad típica vendida (mediana) es: 13.0
El descuento más común (mediana) es: 0.0
El precio típico pagado por transacción (mediana) es: 0.0

### Moda

In [25]:
# ---------- MODA EN TABLA df1 (Ventas) ----------
moda_quantity = df1["Quantity"].mode()[0]
moda_discount = df1["Discount"].mode()[0]
moda_product = df1["ProductID"].mode()[0]
moda_vendedor = df1["SalesPersonID"].mode()[0]

print(">>> MODAS - Tabla df1 (Ventas)")
print(f"Cantidad más común vendida: {moda_quantity}")
print(f"Descuento más frecuente: {moda_discount}")
print(f"ID de producto más vendido: {moda_product}")
print(f"Vendedor más activo (SalesPersonID): {moda_vendedor}")
print()

# ---------- MODA EN TABLA df2 (Productos) ----------
moda_precio = df2["Price"].mode()[0]
moda_clase = df2["Class"].mode()[0]
moda_resistente = df2["Resistant"].mode()[0]
moda_alergico = df2["IsAllergic"].mode()[0]
moda_categoria = df2["CategoryID"].mode()[0]

print(">>> MODAS - Tabla df2 (Productos)")
print(f"Precio más frecuente: {moda_precio}")
print(f"Clase más común: {moda_clase}")
print(f"¿Es resistente más frecuente?: {moda_resistente}")
print(f"¿Es alérgico más frecuente?: {moda_alergico}")
print(f"Categoría más común: {moda_categoria}")

>>> MODAS - Tabla df1 (Ventas)
Cantidad más común vendida: 18
Descuento más frecuente: 0.0
ID de producto más vendido: 161
Vendedor más activo (SalesPersonID): 21

>>> MODAS - Tabla df2 (Productos)
Precio más frecuente: 0.0449
Clase más común: Medium
¿Es resistente más frecuente?: Durable
¿Es alérgico más frecuente?: False
Categoría más común: 1

### Rango Max y Min

### Cuartiles

### RIC -Rango Intercuartil

### Varianza

### Desviación Estandar

## c) Preparación de Datos por Columna

### Conversión de tipos de datos (por ejemplo, fechas o categorías).

In [27]:
df1_cleaned.head(3)

,SalesID,SalesPersonID,CustomerID,ProductID,Quantity,Discount,TotalPrice,SalesDate,TransactionNumber
0,1,6,27039,381,7,0.0,0.0,2018-02-05 07:38:25.430,FQL4S94E4ME1EZFTG42G
1,2,16,25011,61,7,0.0,0.0,2018-02-02 16:03:31.150,12UGLX40DJ1A5DTFBHB8
2,3,13,94024,23,24,0.0,0.0,2018-05-03 19:31:56.880,5DT8RCPL87KI5EORO7B0

In [28]:
print(df1_cleaned.dtypes)

SalesID                int64
SalesPersonID          int64
CustomerID             int64
ProductID              int64
Quantity               int64
Discount             float64
TotalPrice           float64
SalesDate             object
TransactionNumber     object
dtype: object

In [29]:
df1_cleaned['SalesDate'] = pd.to_datetime(df1_cleaned['SalesDate'],)

<ipython-input-29-caa0d9219f4d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_cleaned['SalesDate'] = pd.to_datetime(df1_cleaned['SalesDate'],)

In [30]:
print(df1_cleaned['SalesDate'].dtype)
display(df1_cleaned[['SalesDate']].head())

datetime64[ns]

                SalesDate
0 2018-02-05 07:38:25.430
1 2018-02-02 16:03:31.150
2 2018-05-03 19:31:56.880
3 2018-04-07 14:43:55.420
4 2018-02-12 15:37:03.940

In [31]:
display(df1_cleaned.head(3))

,SalesID,SalesPersonID,CustomerID,ProductID,Quantity,Discount,TotalPrice,SalesDate,TransactionNumber
0,1,6,27039,381,7,0.0,0.0,2018-02-05 07:38:25.430,FQL4S94E4ME1EZFTG42G
1,2,16,25011,61,7,0.0,0.0,2018-02-02 16:03:31.150,12UGLX40DJ1A5DTFBHB8
2,3,13,94024,23,24,0.0,0.0,2018-05-03 19:31:56.880,5DT8RCPL87KI5EORO7B0

In [32]:
print(df1_cleaned.dtypes)

SalesID                       int64
SalesPersonID                 int64
CustomerID                    int64
ProductID                     int64
Quantity                      int64
Discount                    float64
TotalPrice                  float64
SalesDate            datetime64[ns]
TransactionNumber            object
dtype: object

In [33]:
df1_cleaned['Fecha'] = df1_cleaned['SalesDate'].dt.date

<ipython-input-33-1826be725886>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_cleaned['Fecha'] = df1_cleaned['SalesDate'].dt.date

In [34]:
df1_cleaned['hora'] = df1_cleaned['SalesDate'].dt.time

<ipython-input-34-896adcde9d90>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_cleaned['hora'] = df1_cleaned['SalesDate'].dt.time

In [35]:
print(df1_cleaned[['Fecha', 'hora']].head(3))

        Fecha             hora
0  2018-02-05  07:38:25.430000
1  2018-02-02  16:03:31.150000
2  2018-05-03  19:31:56.880000

In [36]:
df1_cleaned_Fechahora= df1_cleaned[['Fecha', 'hora']]

In [37]:
print(df1_cleaned_Fechahora.head(3))

        Fecha             hora
0  2018-02-05  07:38:25.430000
1  2018-02-02  16:03:31.150000
2  2018-05-03  19:31:56.880000

### Imputación de valores faltantes.

In [39]:
precio_dict = dict(zip(df2['ProductID'], df2['Price']))
#Asignar precios a la tabla de ventas
df1_cleaned ['Price'] = df1_cleaned['ProductID'].map(precio_dict)
#Insertar la columna precio en la posicion deseada
df1_cleaned.insert(5, 'Price', df1_cleaned.pop('Price'))
#Agregar la columna subtotal
df1_cleaned ['SubTotal'] = df1_cleaned['Price'] * df1_cleaned['Quantity']

<ipython-input-39-51921d4e5bfa>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_cleaned ['Price'] = df1_cleaned['ProductID'].map(precio_dict)
<ipython-input-39-51921d4e5bfa>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_cleaned ['SubTotal'] = df1_cleaned['Price'] * df1_cleaned['Quantity']

In [40]:
# Configuración de formato para mostrar solo 2 decimales
pd.options.display.float_format = '{:,.2f}'.format
# Visualización
display(df1_cleaned[['Price', 'SubTotal']].head(3))

   Price  SubTotal
0  44.23    309.64
1  62.55    437.82
2  79.02  1,896.44

In [41]:
display(df1_cleaned.head(3))

,SalesID,SalesPersonID,CustomerID,ProductID,Quantity,Price,Discount,TotalPrice,SalesDate,TransactionNumber,Fecha,hora,SubTotal
0,1,6,27039,381,7,44.23,0.00,0.00,2018-02-05 07:38:25.430,FQL4S94E4ME1EZFTG42G,2018-02-05,07:38:25.430000,309.64
1,2,16,25011,61,7,62.55,0.00,0.00,2018-02-02 16:03:31.150,12UGLX40DJ1A5DTFBHB8,2018-02-02,16:03:31.150000,437.82
2,3,13,94024,23,24,79.02,0.00,0.00,2018-05-03 19:31:56.880,5DT8RCPL87KI5EORO7B0,2018-05-03,19:31:56.880000,"1,896.44"

In [45]:
display(Markdown("###Median"))
display(df1_cleaned['SubTotal'].median())
display(Markdown("###Max"))
display(df1_cleaned['SubTotal'].median())
display(Markdown("###Min"))
display(df1_cleaned['SubTotal'].median())

###Median

507.33410000000003

###Max

507.33410000000003

###Min

507.33410000000003

### Criterio para la columna descuentos en ventas
* Ventas de 2500 5 % de descuento
* Ventas de 1000 3 % de descuento
* Ventas de 750  0.5 % de descuento

In [56]:
def calcular_descuento(subtotal):
    if subtotal >= 2500:
        return subtotal * 0.05
    elif subtotal >= 1000 and subtotal <= 1999:
        return subtotal * 0.03
    elif subtotal >= 750 and subtotal <= 999:
        return subtotal * 0.005
    else:
        return 0

In [57]:
df1_cleaned['Discount'] = df1_cleaned['SubTotal'].apply(calcular_descuento)

<ipython-input-57-1945b84b45d3>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_cleaned['Discount'] = df1_cleaned['SubTotal'].apply(calcular_descuento)

In [59]:
display(df1_cleaned.head(3))

,SalesID,SalesPersonID,CustomerID,ProductID,Quantity,Price,Discount,TotalPrice,SalesDate,TransactionNumber,Fecha,hora,SubTotal
0,1,6,27039,381,7,44.23,0.00,309.64,2018-02-05 07:38:25.430,FQL4S94E4ME1EZFTG42G,2018-02-05,07:38:25.430000,309.64
1,2,16,25011,61,7,62.55,0.00,437.82,2018-02-02 16:03:31.150,12UGLX40DJ1A5DTFBHB8,2018-02-02,16:03:31.150000,437.82
2,3,13,94024,23,24,79.02,56.89,"1,839.55",2018-05-03 19:31:56.880,5DT8RCPL87KI5EORO7B0,2018-05-03,19:31:56.880000,"1,896.44"

In [60]:
df1_cleaned['TotalPrice'] = df1_cleaned['SubTotal'] - df1_cleaned['Discount']
display(df1_cleaned.head(3))

<ipython-input-60-ad4a5abdee70>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_cleaned['TotalPrice'] = df1_cleaned['SubTotal'] - df1_cleaned['Discount']

,SalesID,SalesPersonID,CustomerID,ProductID,Quantity,Price,Discount,TotalPrice,SalesDate,TransactionNumber,Fecha,hora,SubTotal
0,1,6,27039,381,7,44.23,0.00,309.64,2018-02-05 07:38:25.430,FQL4S94E4ME1EZFTG42G,2018-02-05,07:38:25.430000,309.64
1,2,16,25011,61,7,62.55,0.00,437.82,2018-02-02 16:03:31.150,12UGLX40DJ1A5DTFBHB8,2018-02-02,16:03:31.150000,437.82
2,3,13,94024,23,24,79.02,56.89,"1,839.55",2018-05-03 19:31:56.880,5DT8RCPL87KI5EORO7B0,2018-05-03,19:31:56.880000,"1,896.44"

## Creación de una Nueva Tabla

In [61]:
## Trabajo TABLA MINABLE Final. :D
df7 = df1_cleaned
df7.head(3)

,SalesID,SalesPersonID,CustomerID,ProductID,Quantity,Price,Discount,TotalPrice,SalesDate,TransactionNumber,Fecha,hora,SubTotal
0,1,6,27039,381,7,44.23,0.00,309.64,2018-02-05 07:38:25.430,FQL4S94E4ME1EZFTG42G,2018-02-05,07:38:25.430000,309.64
1,2,16,25011,61,7,62.55,0.00,437.82,2018-02-02 16:03:31.150,12UGLX40DJ1A5DTFBHB8,2018-02-02,16:03:31.150000,437.82
2,3,13,94024,23,24,79.02,56.89,"1,839.55",2018-05-03 19:31:56.880,5DT8RCPL87KI5EORO7B0,2018-05-03,19:31:56.880000,"1,896.44"

In [62]:
df5.head(2)

  CityID CityName Zipcode  CountryID Ubicacion
0      1   Dayton   80563      32.00      Este
1      2  Buffalo   17420      32.00      Este

In [63]:
df5.columns

Index(['CityID', 'CityName', 'Zipcode', 'CountryID', 'Ubicacion'], dtype='object')

In [75]:
df55 = df1_cleaned.copy()
df55.head(2)

,SalesID,SalesPersonID,CustomerID,ProductID,Quantity,Price,Discount,TotalPrice,SalesDate,TransactionNumber,Fecha,hora,SubTotal
0,1,6,27039,381,7,44.23,0.00,309.64,2018-02-05 07:38:25.430,FQL4S94E4ME1EZFTG42G,2018-02-05,07:38:25.430000,309.64
1,2,16,25011,61,7,62.55,0.00,437.82,2018-02-02 16:03:31.150,12UGLX40DJ1A5DTFBHB8,2018-02-02,16:03:31.150000,437.82

In [71]:
dt_city = df5.copy()
df_city = pd.DataFrame(dt_city)
df_city.head(2)

  CityID CityName Zipcode  CountryID Ubicacion
0      1   Dayton   80563      32.00      Este
1      2  Buffalo   17420      32.00      Este

In [79]:
display(df3.head(3))

,CustomerID,FirstName,MiddleInitial,LastName,CityID,Address,Gender
0,1,Stefanie,Y,Frye,79.00,97 Oak Avenue,F
1,2,Sandy,T,Kirby,96.00,52 White First Freeway,F
2,3,Lee,T,Zhang,55.00,921 White Fabien Avenue,M

In [74]:
data_customer = dict(zip(df3['CustomerID'], zip(df3['Gender'], df_city['CityID']))) # enlazamos sexo y ciudad id
df55['Gender'] = df55['CustomerID'].map(lambda x: 0 if data_customer[x][0] == 'M' else 1)
df55['CityID'] = df55['CustomerID'].map(lambda x: data_customer[x][1])
df55[['Gender','CityID']].head(2)

KeyError: 27039

In [80]:
data_customer = dict(zip(df3['CustomerID'], zip(df3['Gender'], df_city['CityID'])))

# Mapear género con valor por defecto si no se encuentra
df55['Gender'] = df55['CustomerID'].map(
    lambda x: 0 if data_customer.get(x, ('M', None))[0] == 'M' else 1
)

# Mapear CityID con valor por defecto None
df55['CityID'] = df55['CustomerID'].map(
    lambda x: data_customer.get(x, (None, None))[1]
)

df55[['Gender', 'CityID']].head(2)

   Gender CityID
0       0   None
1       0   None

In [82]:
data_customer2 = dict(zip(df_city['CityID'], zip(df_city['CityName'], df_city['Ubicacion'])))

df55['CityZone'] = df55['CityID'].map(
    lambda x: 0 if data_customer2.get(x, (None, None))[1] == 'Este' else 1
)

In [83]:
## nuevo dataframe df55
df55 = df55.sort_values("CustomerID", ascending=False)
df55['CustomerID'].head(3)

5479380    98759
6337873    98759
5459383    98759
Name: CustomerID, dtype: int64

In [84]:
df55['TotalPrice'].head(5)

5479380     582.11
6337873     710.16
5459383     705.58
1245677   2,153.34
2453865     988.48
Name: TotalPrice, dtype: float64

In [87]:
df55_grouped = df55.groupby(['CustomerID']).agg({
    'TotalPrice':'sum',
    'Discount': 'mean',
    'CityZone': 'first',
    'Gender': 'first'
}).reset_index()

df55_grouped = df55_grouped.rename(columns={
    'TotalPrice': 'SumaComp',
    'Discount': 'PromDesct',
    'CityZone': 'CityZone',
    'Gender': 'Gender'
})

In [88]:
# calculamos independientemente lo que necesitamos
df55_countPrice = df55.groupby(['CustomerID']).agg({'TotalPrice':'count'}) # contarVentastotales
df55_meanPrice = df55.groupby(['CustomerID']).agg({'TotalPrice':'mean'})   # promedioVentastotales

# Renombramos las columnas
df55_countTPrice = df55_countPrice.rename(columns={'TotalPrice': 'CantCompras'})
df55_meanPrice = df55_meanPrice.rename(columns={'TotalPrice': 'PromedioCompra'})

# Unimos las 2 columnas calculadas
df55_stats = df55_countPrice.join(df55_meanPrice)

# Unimos las 2 columnas calculadasa df55_grouped que es la base minable
df55_grouped = df55_grouped.join(df55_stats, on='CustomerID')

df55_grouped.head(3)

,CustomerID,SumaComp,PromDesct,CityZone,Gender,TotalPrice,PromedioCompra
0,1,"3,246.61",0.00,1,0,63,51.53
1,2,"3,414.55",0.00,1,0,63,54.20
2,3,"3,392.44",0.00,1,0,70,48.46

In [89]:
df55_grouped = df55_grouped.rename(columns={'TotalPrice': 'CantCompras'})
df55_grouped.head(2)

,CustomerID,SumaComp,PromDesct,CityZone,Gender,CantCompras,PromedioCompra
0,1,"3,246.61",0.00,1,0,63,51.53
1,2,"3,414.55",0.00,1,0,63,54.20

In [90]:
# analisis de campo promDesct para verificar ceros y contenido
print((df55_grouped['PromDesct'] > 1).sum())
print((df55_grouped['PromDesct'] == 0).sum())

62048
27767

In [91]:
## Normalizacion de datos
dfMinable = df55_grouped.copy()

In [93]:
display(dfMinable.head(10))

,CustomerID,SumaComp,PromDesct,CityZone,Gender,CantCompras,PromedioCompra
0,1,"3,246.61",0.00,1,0,63,51.53
1,2,"3,414.55",0.00,1,0,63,54.20
2,3,"3,392.44",0.00,1,0,70,48.46
3,4,"3,235.63",0.00,1,0,69,46.89
4,5,"2,772.36",0.00,1,0,59,46.99
5,6,"4,163.16",0.00,1,0,73,57.03
6,7,"3,803.56",0.00,1,0,71,53.57
7,8,"3,304.29",0.00,1,0,58,56.97
8,9,"2,907.88",0.00,1,0,65,44.74
9,10,"3,042.46",0.00,1,0,55,55.32

## Estandarización (Normalización Z-Score)

Este método transforma los datos de tal manera que tengan **media 0** y **desviación estándar 1**. Es útil cuando tus datos siguen una distribución normal.

### Fórmula:

$$
x_{\text{estandarizado}} = \frac{x - \mu}{\sigma}
$$

donde:
- $\mu$ es la **media** de la columna.
- $\sigma$ es la **desviación estándar** de la columna.

### Ventajas:
- Reduce el impacto de *outliers*.
- Útil para algoritmos sensibles a la escala, como **K-Means**.

### Desventajas:
- Puede distorsionar la distribución original.